import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        tertiary: "#000000",
        "on-surface-variant": "#45464d",
        "surface-variant": "#d3e4fe",
        "secondary-fixed-dim": "#c4c6d1",
        "surface-container-highest": "#d3e4fe",
        "tertiary-fixed": "#fcdeb5",
        "primary-container": "#131b2e",
        "surface-tint": "#565e74",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "secondary-container": "#dedfeb",
        "tertiary-container": "#271901",
        primary: "#000000",
        "on-background": "#0b1c30",
        "on-tertiary-fixed-variant": "#574425",
        "surface-container": "#e5eeff",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed": "#131b2e",
        "tertiary-fixed-dim": "#dec29a",
        "on-surface": "#0b1c30",
        "on-primary-container": "#7c839b",
        "on-secondary-fixed-variant": "#444650",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-low": "#eff4ff",
        background: "#f8f9ff",
        "inverse-surface": "#213145",
        "on-secondary-fixed": "#191b24",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#60626c",
        "inverse-primary": "#bec6e0",
        secondary: "#5c5e68",
        outline: "#76777d",
        "outline-variant": "#c6c6cd",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#98805d",
        "secondary-fixed": "#e1e2ed",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#271901",
        "on-tertiary": "#ffffff",
        accent: {
          DEFAULT: "#3B82F6",
          dark: "#2563EB",
          50: "#EFF6FF",
          100: "#DBEAFE",
          200: "#BFDBFE",
          700: "#1D4ED8",
        },
        status: {
          present: "#22C55E",
          "on-leave": "#F59E0B",
          absent: "#EAB308",
          pending: "#94A3B8",
          approved: "#22C55E",
          rejected: "#EF4444",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        base: "4px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        margin: "32px",
        sidebar: "260px",
        topbar: "64px",
      },
      fontFamily: {
        display: ["Geist", "Inter", "sans-serif"],
        "headline-md": ["Geist", "Inter", "sans-serif"],
        "headline-lg": ["Geist", "Inter", "sans-serif"],
        "mono-sm": ["Geist Mono", "monospace"],
        "label-md": ["Geist", "Inter", "sans-serif"],
        "body-lg": ["Geist", "Inter", "sans-serif"],
        "body-md": ["Geist", "Inter", "sans-serif"],
        sans: ["Geist", "Inter", "sans-serif"],
      },
      fontSize: {
        display: ["36px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "mono-sm": ["12px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
